--CREATE TYPE IF NOT EXISTS rating AS ENUM ('G', 'PG', 'PG13', 'R', 'NC17');
--CREATE TYPE IF NOT EXISTS genre AS ENUM ('COMEDY', 'DRAMA', 'CARTOON', 'THRILLER', 'DOCUMENTARY', 'ACTION');

CREATE TABLE IF NOT EXISTS genres (
	id Integer generated by default as identity primary key,
	name VARCHAR
);

CREATE TABLE IF NOT EXISTS ratings (
	id INTEGER generated by default as identity primary key,
	name VARCHAR
);

CREATE TABLE IF NOT EXISTS films (
	id INTEGER generated by default as identity primary key,
	name VARCHAR(200),
	description VARCHAR,
	release_date timestamp,
	duration INTEGER,
	genre_id Integer,
	rating_id Integer,
	CONSTRAINT fk_films_genre_id FOREIGN KEY(genre_id) REFERENCES genres(id),
	CONSTRAINT fk_films_rating_id FOREIGN KEY(rating_id) REFERENCES ratings(id)
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER generated by default as identity primary key,
	email VARCHAR,
	login VARCHAR,
	name VARCHAR,
	birthday timestamp
);

CREATE TABLE IF NOT EXISTS films_likes (
	film_id INTEGER,
	user_id INTEGER,
	CONSTRAINT fk_films_likes_film_id FOREIGN KEY(film_id) REFERENCES films(id),
	CONSTRAINT fk_films_likes_user_id FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TYPE IF NOT EXISTS friend_status AS ENUM ('CONFIRMED', 'REQUESTED', 'REQUEST');

CREATE TABLE IF NOT EXISTS friends (
	user_id INTEGER,
	friend_id INTEGER,
	status friend_status,
	CONSTRAINT fk_friends_user_id FOREIGN KEY(user_id) REFERENCES users(id),
	CONSTRAINT fk_friends_friend_id FOREIGN KEY(friend_id) REFERENCES users(id)
);